In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('D:/datasets/jobsalary.csv')

In [5]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [2]:
df.shape

NameError: name 'df' is not defined

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
abc = df['job_title'].value_counts()

In [9]:
df['job_title'].value_counts().sort_values().plot(kind='barh')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [ ]:
df['job_title'].value_counts().sort_values().plot(
    kind='barh',
    figsize=(8,5),
    color='skyblue',
    grid=True,
    title='Job Profile Count'
)

plt.xlabel("Count")
plt.ylabel("Job Role")
plt.show()

In [ ]:
df.sample(3)

In [ ]:
df.columns

In [ ]:
df.groupby('location')['salary'].median()

In [ ]:
df.groupby('job_title')['experience_years'].mean()

In [26]:
x = df.drop('salary' ,axis=1)

In [27]:
y = df[['salary']]

In [28]:
y

        salary
0       109413
1        93764
2       148123
3       189123
4       165069
...        ...
249995  127791
249996  154593
249997   75988
249998   90467
249999  133084

[250000 rows x 1 columns]

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [30]:
categorical_features = [
    'job_title', 'education_level', 'industry',
    'company_size', 'location', 'remote_work'
]

numeric_features = [
    'experience_years', 'skills_count', 'certifications'
]

In [31]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

In [32]:
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['job_title',
                                                   'education_level',
                                                   'industry', 'company_size',
                                                   'location',
                                                   'remote_work'])])),
                ('regressor', LinearRegression())])

In [34]:
y_pred = model.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 5513.95699039839
R2 Score: 0.9627528786097451

In [38]:
import joblib

joblib.dump(model, "models.pkl")

['models.pkl']

In [22]:
df.columns

Index(['job_title', 'experience_years', 'education_level', 'skills_count',
       'industry', 'company_size', 'location', 'remote_work', 'certifications',
       'salary'],
      dtype='str')

In [23]:
abc

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

In [6]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
encoder = OneHotEncoder(sparse_output=False)

In [18]:
result  = encoder.fit_transform(df[['job_title']])

In [21]:
result[0:2]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [1]:
import mlflow

In [ ]:
mlflow.set_experiment('First Experiement')
mlflow.set_tracking_uri('http://127.0.0.1:5000/')