In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('D:/datasets/Teen_Mental_Health_Dataset.csv')

In [7]:
df.sample()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
230,17,male,2.4,TikTok,8.5,2.4,2.79,1.1,low,1,6,7,0

In [5]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='str')

In [9]:
df['depression_label'].value_counts()

depression_label
0    1169
1      31
Name: count, dtype: int64

In [15]:
x = df.drop('depression_label', axis=1)

In [17]:
y = df[['depression_label']]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)

In [21]:
x_train

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level
368,13,male,2.4,Instagram,7.1,0.7,3.64,1.1,high,6,5,5
217,19,male,4.9,TikTok,4.5,2.9,3.88,0.8,low,5,5,6
541,13,female,7.8,Instagram,7.4,1.7,2.76,1.1,low,10,1,4
67,17,male,5.8,Both,7.6,0.7,2.83,1.0,medium,7,6,8
436,19,male,3.5,TikTok,5.8,1.8,3.30,0.9,low,7,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...
775,14,male,4.9,Instagram,5.5,1.6,2.85,0.4,low,8,1,8
306,15,male,3.0,Instagram,8.6,1.5,3.27,0.8,medium,10,10,4
759,18,male,3.6,Instagram,4.7,2.5,2.73,1.2,medium,9,7,6
807,14,female,1.3,TikTok,7.5,1.4,3.85,1.6,medium,10,8,7
82,14,male,1.2,Both,5.2,2.2,2.19,1.9,medium,9,9,4

In [23]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [24]:
from sklearn.compose import ColumnTransformer

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
trans = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(sparse_output=False), [1, 3, 8])
    ],
    remainder='passthrough'
)

In [27]:
from sklearn.pipeline import Pipeline

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
pipe = Pipeline(steps=[
    ('trans' ,trans), 
    ('model' ,DecisionTreeClassifier())
    
])

In [60]:
pipe.named_steps['trans']

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehot', OneHotEncoder(sparse_output=False),
                                 [1, 3, 8])])

In [30]:
pipe.fit(x_train , y_train)

Pipeline(steps=[('trans',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot',
                                                  OneHotEncoder(sparse_output=False),
                                                  [1, 3, 8])])),
                ('model', DecisionTreeClassifier())])

In [31]:
y_pre = pipe.predict(x_test)

In [32]:
y_pre

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
from sklearn.metrics import mean_absolute_error, r2_score ,accuracy_score

print("MAE:", mean_absolute_error(y_test, y_pre))
print("R2 Score:", r2_score(y_test, y_pre))

MAE: 0.0
R2 Score: 1.0

In [36]:
accuracy_score(y_test , y_pre)

1.0

In [37]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [50]:
df['platform_usage'].value_counts()

platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

In [51]:
np.round(df.groupby('platform_usage')['screen_time_before_sleep'].mean()*60)

platform_usage
Both         105.0
Instagram    103.0
TikTok       106.0
Name: screen_time_before_sleep, dtype: float64

In [56]:
df.groupby('platform_usage')['sleep_hours'].mean()*60

platform_usage
Both         387.774936
Instagram    386.379562
TikTok       386.773869
Name: sleep_hours, dtype: float64

In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('flights')

In [3]:
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [7]:
df['passengers'].values

array([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115,
       126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150,
       178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193,
       181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235,
       229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234,
       264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315,
       364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413,
       405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467,
       404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404,
       359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407,
       362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390,
       432])

In [15]:
round(df.groupby('month')['passengers'].mean())

month
Jan    242.0
Feb    235.0
Mar    270.0
Apr    267.0
May    272.0
Jun    312.0
Jul    351.0
Aug    351.0
Sep    302.0
Oct    267.0
Nov    233.0
Dec    262.0
Name: passengers, dtype: float64

In [1]:
import seaborn as sns